[Signature]
ID=00000000000000000000000000000000

[Version]
ID=G1701CA Version: C.00.00

[General]
Type=6
Inlet=0
Start Mode=0
Run Duration=720
Solvent Delay=2
Tune File=HES_Atune.u
Group Ions=6
Acq Mode=3
Gauges=2
Fast Scan=0
TID=1
EMSaver=0

[Zone 1]
ID=1
On=1
Soft Max=200
Set Point=150
Type=0

[Zone 2]
ID=0
On=1
Soft Max=250
Set Point=230
Type=0

[Zone 3]
ID=-1
On=0
Soft Max=0
Set Point=0
Type=0

[Ions 1]
Group Name=Biphenyl
Start Time=2
Resolution=0
Number of Ions=3
Ion 1=76.00,25
Group EMV Setting=0
Use Group EMV Setting=false
IonL1=
Ion 2=154.00,25
IonL2=
Ion 3=240.00,25
IonL3=
Ion 4=76.00,100
IonL4=
Plot Index 1=0
Plot Index 2=1

[Scan 1]
Start Time=2
Low Mass=41
High Mass=250
Threshold=0
Sampling=4
Low Plot 1=
Low Plot 2=
High Plot 1=
High Plot 2=

[Scan 2]

[Scan 3]

[Filters]
Mass Type=0
Mass Param=0
Mass Sigma=0
Time Type=0
Time Param=0
Time Sigma=0

[Plot]
Plot Type 1=0
Time Plot 1=0
Min Plot 1=0
Max Plot 1=0
Left Plot 1=0.000000
Top Plot 1=0.085653
Width Plot 1=0.520196
Height Plot 1=0.625268
Mode Plot 1=2
Plot Type 2=2
Time Plot 2=0
Min Plot 2=0
Max Plot 2=0
Left Plot 2=0.198286
Top Plot 2=0.197002
Width Plot 2=0.499388
Height Plot 2=0.501071
Mode Plot 2=2
X Gadget Pos 1=5
Y Gadget Pos 1=230
X Gadget Pos 2=130
Y Gadget Pos 2=230
Low Mass 1=0.6
High Mass 1=1091
Plot Label 1=
Low Mass 2=0.6
High Mass 2=1091
Plot Label 2=

[Gauge1]
Type=2
ID=1
Display Type=0
Left Plot=380
Top Plot=230
Alarm Error=100.00
Alarm Warning=100.00
Alarm Minimum=0.00
Alarm Set=0

[Gauge2]
Type=2
ID=0
Display Type=0
Left Plot=255
Top Plot=230
Alarm Error=100.00
Alarm Warning=100.00
Alarm Minimum=0.00
Alarm Set=0

[Parameters]
ID 1=7
Mode 1=2
Value 1=1.000000
ID 2=-1
Mode 2=0
Value 2=0.000000

[Time Events]
Number Events=0
[SCIS]
H2FlowRate=0.13
Emission=10
SourceTemperature=230
QuadrupoleTemperature=150
Duration=1.3
StabilizationDuration=0.166666666666667
Filament=2
Mode=None
[Ions 2]
Group Name=Chlorobiphenyl
Start Time=5.2
Resolution=0
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=2
Number of Ions=3
Ion 1=76.00,25
IonL1=
Ion 2=152.00,25
IonL2=
Ion 3=188.00,25
IonL3=
[Ions 3]
Group Name=PETN
Start Time=7.4
Resolution=0
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=0
Number of Ions=3
Ion 1=46.00,25
IonL1=
Ion 2=57.00,25
IonL2=
Ion 3=76.00,25
IonL3=
[Ions 4]
Group Name=RDX
Start Time=8.3
Resolution=0
Group EMV Setting=0
Use Group EMV Setting=false
Number of Ions=3
Ion 1=46.00,25
IonL1=
Ion 2=75.00,25
IonL2=
Ion 3=128.00,25
IonL3=
[Ions 5]
Group Name=Musk Tibetine
Start Time=8.7
Resolution=0
Group EMV Setting=0
Use Group EMV Setting=false
Number of Ions=3
Ion 1=43.00,25
IonL1=
Ion 2=77.00,25
IonL2=
Ion 3=91.00,25
IonL3=
[Ions 6]
Group Name=Methyl Palmitate
Start Time=8.95
Resolution=0
Group EMV Setting=0
Use Group EMV Setting=false
Number of Ions=3
Ion 1=74.00,25
IonL1=
Ion 2=87.00,25
IonL2=
Ion 3=143.00,25
IonL3=
[Ions 7]
Group Name=RDX
Start Time=6.5
Resolution=0
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=1
Plot Index 2=2
Number of Ions=3
Ion 1=30.00,25
IonL1=
Ion 2=42.00,25
IonL2=
Ion 3=46.00,25
IonL3=
