### Combine ImageJ threshold results into Summary.csv format ###
# This script reads the 100 threshold CSVs generated by ImageJ for each image
# and combines them into a single Summary.csv file (300 rows) for each Surface/Rep
#
# PREREQUISITE: 
#   1. Run 00-GlobalCode.R first
#   2. Run 01-OrganizeImages.R to organize images
#   3. Process images in ImageJ using the corrected macro (ImageJ_ThresholdMacro.txt)
#      which saves the Summary table (not individual particle results)

# === HELPER FUNCTION TO READ %Area FROM SUMMARY CSV ===

read_percent_area <- function(folder_path, image_name) {
  # Read all CSVs for one image type (Blank, Before, or After)
  # Expected naming: ImageName[k].csv where k = 1 to 100
  
  area_values <- numeric(100)
  files_found <- 0
  
  for (k in 1:100) {
    # Construct expected filename
    csv_pattern <- paste0(image_name, "\\[", k, "\\]\\.csv$")
    csv_file <- list.files(path = folder_path, pattern = csv_pattern, full.names = TRUE)
    
    if (length(csv_file) == 0) {
      # Try alternative pattern without escaping
      csv_file <- list.files(path = folder_path, pattern = paste0(image_name, "[", k, "].csv$"), full.names = TRUE)
    }
    
    if (length(csv_file) >= 1) {
      files_found <- files_found + 1
      
      # Read the CSV
      csv_data <- read.csv(csv_file[1])
      
      # Extract %Area column
      if ("%Area" %in% names(csv_data)) {
        area_values[k] <- csv_data[["%Area"]][1]
      } else if ("X..Area" %in% names(csv_data)) {
        area_values[k] <- csv_data[["X..Area"]][1]
      } else {
        # Try to find any column containing "Area"
        area_cols <- grep("Area", names(csv_data), value = TRUE, ignore.case = TRUE)
        if (length(area_cols) > 0) {
          # Use the %Area column if available, otherwise use Total Area
          pct_col <- grep("%Area|^X\\.\\.Area$", area_cols, value = TRUE)
          if (length(pct_col) > 0) {
            area_values[k] <- csv_data[[pct_col[1]]][1]
          } else {
            area_values[k] <- csv_data[[area_cols[1]]][1]
          }
        } else {
          warning(sprintf("No Area column found in %s", basename(csv_file[1])))
          area_values[k] <- NA
        }
      }
    } else {
      area_values[k] <- NA
    }
  }
  
  return(list(values = area_values, files_found = files_found))
}

# === PROCESS EACH SURFACE/REP FOLDER ===

# Get list of Surface_Rep folders
surface_folders <- list.dirs(OrganizedImages.dir, recursive = FALSE, full.names = TRUE)
surface_folder_names <- basename(surface_folders)

cat(sprintf("\n=== COMBINING IMAGEJ RESULTS ===\n"))
cat(sprintf("Found %d Surface/Rep folders to process\n", length(surface_folders)))

# Track processed folders for cleanup
processed_folders <- c()

for (folder in surface_folders) {
  folder_name <- basename(folder)
  cat(sprintf("\n=== Processing: %s ===\n", folder_name))
  
  # Check if there are TIF files (image files present)
  tif_files <- list.files(folder, pattern = "\\.tif$", full.names = FALSE)
  
  if (length(tif_files) == 0) {
    cat(sprintf("  SKIPPED: No image files found\n", folder_name))
    next
  }
  
  # Determine image base names from TIF files
  image_names <- tools::file_path_sans_ext(tif_files)
  
  cat(sprintf("  Found images: %s\n", paste(image_names, collapse = ", ")))
  
  # Create results data frame
  results <- data.frame(
    Slice = paste0("Slice_K_", 100:1),
    X.Area = numeric(300)
  )
  
  all_found <- TRUE
  
  # Process each image type
  for (img_name in image_names) {
    cat(sprintf("  Processing %s...\n", img_name))
    
    # Get %Area values for all 100 thresholds
    area_data <- read_percent_area(folder, img_name)
    area_values <- area_data$values
    files_found <- area_data$files_found
    
    cat(sprintf("    %d threshold files found\n", files_found))
    
    # Determine which rows to fill based on image type
    if (grepl("blank", img_name, ignore.case = TRUE)) {
      row_start <- 1
      row_end <- 100
    } else if (grepl("before", img_name, ignore.case = TRUE)) {
      row_start <- 101
      row_end <- 200
    } else if (grepl("after", img_name, ignore.case = TRUE)) {
      row_start <- 201
      row_end <- 300
    } else {
      # Assign based on order found
      img_index <- which(image_names == img_name)
      row_start <- (img_index - 1) * 100 + 1
      row_end <- img_index * 100
    }
    
    # Fill in values (reverse order to match expected format: threshold 100 to 1)
    results$X.Area[row_start:row_end] <- rev(area_values)
    
    # Check if all files found
    if (files_found < 100) {
      all_found <- FALSE
      cat(sprintf("    WARNING: Only %d of 100 threshold files found\n", files_found))
    }
  }
  
  # Save Summary.csv
  output_folder <- file.path(ThresholdResults.dir, folder_name)
  dir.create(output_folder, recursive = TRUE, showWarnings = FALSE)
  
  output_path <- file.path(output_folder, "Summary.csv")
  write.csv(results, file = output_path, row.names = FALSE)
  
  cat(sprintf("  Saved: %s\n", output_path))
  
  # Mark folder as processed for cleanup
  if (all_found) {
    processed_folders <- c(processed_folders, folder)
  }
}

# === SUMMARY ===

cat("\n=== COMBINATION SUMMARY ===\n")
cat(sprintf("Processed %d Surface/Rep combinations\n", length(processed_folders)))
cat(sprintf("Output saved to: %s\n", ThresholdResults.dir))

# List created Summary.csv files
cat("\nCreated files:\n")
summary_files <- list.files(ThresholdResults.dir, pattern = "Summary.csv", recursive = TRUE, full.names = TRUE)
for (f in summary_files) {
  folder <- basename(dirname(f))
  cat(sprintf("  %s/Summary.csv\n", folder))
  
  # Quick validation
  data <- read.csv(f)
  cat(sprintf("    - %d rows, %d columns\n", nrow(data), ncol(data)))
  if ("X.Area" %in% names(data)) {
    non_na <- sum(!is.na(data$X.Area))
    cat(sprintf("    - %d non-NA values, range: %.2f to %.2f\n", non_na, min(data$X.Area, na.rm = TRUE), max(data$X.Area, na.rm = TRUE)))
  }
}

# === CLEANUP: DELETE INDIVIDUAL CSV FILES ===

cat("\n=== CLEANUP: DELETING INDIVIDUAL CSV FILES ===\n")

total_deleted <- 0

for (folder in processed_folders) {
  folder_name <- basename(folder)
  
  # Verify Summary.csv exists for this folder
  summary_path <- file.path(ThresholdResults.dir, folder_name, "Summary.csv")
  
  if (file.exists(summary_path)) {
    # Find all individual threshold CSV files matching pattern [k].csv
    csv_files <- list.files(folder, pattern = "\\[\\d+\\]\\.csv$", full.names = TRUE)
    
    if (length(csv_files) > 0) {
      # Delete the files
      file.remove(csv_files)
      total_deleted <- total_deleted + length(csv_files)
      cat(sprintf("  %s: Deleted %d CSVs\n", folder_name, length(csv_files)))
    }
  } else {
    cat(sprintf("  SKIPPED %s: Summary.csv not found\n", folder_name))
  }
}

cat(sprintf("\nTotal CSV files deleted: %d\n", total_deleted))
cat("\nFolders tidied. Only Summary.csv files remain in OrganizedImages.\n")

cat("\n=== SCRIPT COMPLETE ===\n")
