[Signature]
ID=00000000000000000000000000000000

[Version]
ID=G1701CA Version: C.00.00

[General]
Type=6
Inlet=0
Start Mode=0
Run Duration=39000
Solvent Delay=3
Tune File=stune.u
Group Ions=7
Acq Mode=0
Gauges=2
Fast Scan=0
TID=0
EMSaver=0

[Zone 1]
ID=1
On=1
Soft Max=200
Set Point=150
Type=0

[Zone 2]
ID=0
On=1
Soft Max=250
Set Point=230
Type=0

[Zone 3]
ID=-1
On=0
Soft Max=0
Set Point=0
Type=0

[Ions 1]
Group Name=1
Start Time=3
Resolution=1
Plot Index 1=0
Number of Ions=1
Ion 1=74.10,100
Group EMV Setting=0
Use Group EMV Setting=false
IonL1=

[Scan 1]
Start Time=3
Low Mass=40
High Mass=450
Threshold=150
Sampling=4
Low Plot 1=
Low Plot 2=
High Plot 1=
High Plot 2=

[Scan 2]

[Scan 3]

[Filters]
Mass Type=0
Mass Param=0
Mass Sigma=0
Time Type=0
Time Param=0
Time Sigma=0

[Plot]
Plot Type 1=0
Time Plot 1=0
Min Plot 1=0
Max Plot 1=0
Left Plot 1=0.000000
Top Plot 1=0.085653
Width Plot 1=0.520196
Height Plot 1=0.625268
Mode Plot 1=2
Plot Type 2=2
Time Plot 2=0
Min Plot 2=0
Max Plot 2=0
Left Plot 2=0.198286
Top Plot 2=0.197002
Width Plot 2=0.499388
Height Plot 2=0.501071
Mode Plot 2=2
X Gadget Pos 1=5
Y Gadget Pos 1=230
X Gadget Pos 2=130
Y Gadget Pos 2=230
Low Mass 1=1.6
High Mass 1=1050
Plot Label 1=
Low Mass 2=1.6
High Mass 2=1050
Plot Label 2=

[Gauge1]
Type=2
ID=1
Display Type=0
Left Plot=380
Top Plot=230
Alarm Error=100.00
Alarm Warning=100.00
Alarm Minimum=0.00
Alarm Set=0

[Gauge2]
Type=2
ID=0
Display Type=0
Left Plot=255
Top Plot=230
Alarm Error=100.00
Alarm Warning=100.00
Alarm Minimum=0.00
Alarm Set=0

[Parameters]
ID 1=7
Mode 1=2
Value 1=1.000000
ID 2=-1
Mode 2=0
Value 2=0.000000

[Time Events]
Number Events=0
[Ions 2]
Group Name=Diazepam
Start Time=12
Resolution=1
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=0
Plot Index 2=1
Plot Index 3=2
Number of Ions=3
Ion 1=221.10,100
IonL1=
Ion 2=256.10,100
IonL2=
Ion 3=283.10,100
IonL3=
[Ions 3]
Group Name=Flubro+ Dicla
Start Time=13
Resolution=1
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=0
Plot Index 2=1
Plot Index 3=2
Plot Index 4=3
Plot Index 5=4
Plot Index 6=5
Number of Ions=6
Ion 1=255.10,100
IonL1=Flubromazepam
Ion 2=290.10,100
IonL2=Flubromazepam
Ion 3=305.00,100
IonL3=Diclazepam
Ion 4=315.00,100
IonL4=Diclazepam
Ion 5=318.10,100
IonL5=Flubromazepam
Ion 6=333.00,100
IonL6=Diclazepam
[Ions 4]
Group Name=Phenazepam + nitrazepam
Start Time=14
Resolution=1
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=0
Plot Index 2=1
Plot Index 3=2
Plot Index 4=3
Plot Index 5=4
Plot Index 6=5
Number of Ions=6
Ion 1=234.10,100
IonL1=Nitrazepam
Ion 2=253.10,100
IonL2=Nitrazepam
Ion 3=280.10,100
IonL3=Nitrazepam
Ion 4=313.00,100
IonL4=Phenazepam
Ion 5=321.00,100
IonL5=Phenazepam
Ion 6=350.00,100
IonL6=Phenazepam
[Ions 5]
Group Name=Clonazepam
Start Time=15
Resolution=1
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=0
Plot Index 2=1
Plot Index 3=2
Number of Ions=3
Ion 1=280.10,100
IonL1=
Ion 2=288.00,100
IonL2=
Ion 3=314.10,100
IonL3=
[Ions 6]
Group Name=Alprazolam
Start Time=16
Resolution=1
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=0
Plot Index 2=1
Plot Index 3=2
Number of Ions=3
Ion 1=204.10,100
IonL1=
Ion 2=279.10,100
IonL2=
Ion 3=308.10,100
IonL3=
[Ions 7]
Group Name=Etizolam
Start Time=17
Resolution=1
Group EMV Setting=0
Use Group EMV Setting=false
Plot Index 1=0
Plot Index 2=1
Plot Index 3=2
Number of Ions=3
Ion 1=273.10,100
IonL1=
Ion 2=313.10,100
IonL2=
Ion 3=342.10,100
IonL3=
