#===============================================================================
# investigate_rdx_batch_effect.R
#
# Consolidated, re-runnable version of the RDX batch-to-batch recovery
# investigation from the August 10, 2026 session (see CONTEXT.md session
# summary "RDX Batch-to-Batch Recovery Investigation" for the full narrative
# and conclusions). This script re-derives every check performed in that
# session from source data, so it can be extended/re-run as more batches are
# collected or as pilot_data_lab_notes.xlsx is updated with new lab records.
#
# Requires: pilot_data_lab_notes.xlsx (in the study output_dir, see below) --
# a manually-maintained lab-notes workbook (Humidity, Time Cleaned/Spiked/
# Swabbed, Date Extracted, Swab Batch, ASTRA Platform?) layered on top of the
# same schema as pilot_data_nested.csv. NOT auto-generated by pilot_analysis.R
# -- if it doesn't exist, only the sections requiring GC-MS raw data (shape
# comparison, IS mechanism check) can be run; the lab-notes-dependent sections
# (Platform/SwabBatch/Humidity/DryingTime/ExtractionDelay) will fail cleanly.
#
# Author: <add name>
# License: GNU AGPL v3
#===============================================================================

suppressPackageStartupMessages({
  library(readxl)
  library(dplyr)
  library(lme4)
  library(lmerTest)
})

#-------------------------------------------------------------------------------
# CONFIGURATION
#-------------------------------------------------------------------------------
output_dir <- "C:/Users/A Bruce - User/OneDrive - University of Dundee/Documents/Experimental Results/ASTRA Swabbing/Pilot Study"
gc_data_dir <- file.path(output_dir, "GC Data")
lab_notes_file <- file.path(output_dir, "pilot_data_lab_notes.xlsx")

# Discover Analysis folders automatically (don't hardcode -- new batches will
# add new Analysis folders over time)
analysis_dirs <- list.dirs(gc_data_dir, recursive = FALSE)
analysis_dirs <- analysis_dirs[grepl("^Analysis\\d+$", basename(analysis_dirs))]
datasets <- basename(analysis_dirs)
cat("Discovered Analysis datasets:", paste(datasets, collapse = ", "), "\n\n")

#-------------------------------------------------------------------------------
# 1. LOAD DATA
#-------------------------------------------------------------------------------

# Raw per-injection GC-MS results (for rdx_pa / rdx_is_pa / rdx_ratio -- the
# untransformed signal chain, needed for the shape and IS-mechanism checks)
raw <- bind_rows(lapply(datasets, function(d) {
  f <- file.path(gc_data_dir, d, "Results", paste0(d, "_GCMSResults.csv"))
  if (!file.exists(f)) return(NULL)
  df <- read.csv(f, stringsAsFactors = FALSE)
  df$Dataset <- d
  df$SampleName_trimmed <- trimws(df$SampleName)
  df
}))

if (!file.exists(lab_notes_file)) {
  stop("pilot_data_lab_notes.xlsx not found at: ", lab_notes_file,
       " -- lab-notes-dependent sections of this script cannot run without it.")
}

lab <- as.data.frame(read_excel(lab_notes_file, sheet = "pilot_data_nested"))
pilot <- lab[!is.na(lab$SampleType) & lab$SampleType == "Pilot", ]

pilot$EventDate           <- as.Date(pilot$Test_DateTime)
pilot$ElapsedDays         <- as.numeric(pilot$EventDate - min(pilot$EventDate))
pilot$BatchNumeric        <- as.numeric(pilot$BatchNumber)
pilot$BatchNumber         <- factor(pilot$BatchNumber)
pilot$DryingTime_min      <- as.numeric(difftime(pilot$`Time Swabbed`, pilot$`Time Spiked`, units = "mins"))
pilot$CleanToSpike_min    <- as.numeric(difftime(pilot$`Time Spiked`, pilot$`Time Cleaned`, units = "mins"))
pilot$ExtractionDelay_days<- as.numeric(difftime(as.Date(pilot$`Date Extracted`), as.Date(pilot$Test_DateTime), units = "days"))
pilot$SwabBatch           <- factor(pilot$`Swab Batch`)
pilot$Platform            <- factor(pilot$`ASTRA Platform?`)
pilot$Dataset             <- basename(pilot$AnalysisFolder)
pilot$SurfaceID_nested    <- interaction(pilot$Surface_type, pilot$SurfaceID, drop = TRUE)

# Join in the raw GC-MS signal chain (rdx_pa/rdx_is_pa/rdx_ratio) for each
# pilot sample's SELECTED attempt (matched on Dataset + RunID, matching how
# pilot_analysis.R's own select_best_attempt() resolves reanalysed samples)
pilot <- pilot %>%
  left_join(raw %>% select(Dataset, SampleName_trimmed, rdx_pa, rdx_is_pa, rdx_ratio, Line),
            by = c("Dataset", RunID = "SampleName_trimmed"))

cat("Pilot rows loaded:", nrow(pilot), "\n\n")

#-------------------------------------------------------------------------------
# 2. BUILD TRUE PHYSICAL-SURFACE USAGE HISTORY (pilot + NC combined)
#-------------------------------------------------------------------------------
# NCs reuse the SAME physical surfaces as real pilot samples (confirmed
# directly -- there are no separate "spare" control surfaces). To test a
# "surface wear" hypothesis properly, NC swabs must count as uses too, and
# must be placed in the CORRECT chronological position -- NCs are taken at
# the START of their own batch's session, not the end (confirmed with the
# user directly). Matching an NC to "its own batch's pilot samples" is done
# in two tiers:
#   Tier 1: match on (SurfaceID, EventDate, BatchNumber) -- works for the
#           great majority of NCs, whose BatchNumber label matches a real
#           pilot BatchNumber run on the same surface that day.
#   Tier 2 (fallback): match on (SurfaceID, EventDate, TestOrder) instead --
#           needed for the one orphan case seen so far ("ABSBatch5 NC"),
#           whose BatchNumber=5 doesn't correspond to any real pilot batch;
#           "5" is actually a TestOrder marker for a delayed catch-up
#           session, not a batch number.
# Both tiers were verified explicitly against all 9 NCs present as of this
# session (8 matched Tier 1, 1 matched Tier 2) -- re-verify this assumption
# if a NEW orphan-style NC label appears in future lab notes.

all_dated <- lab
all_dated$EventDate <- as.Date(all_dated$Test_DateTime)
all_dated$TimeSpikedChar <- format(all_dated$`Time Spiked`, "%H:%M:%S")

pilot_times_batch <- all_dated %>%
  filter(SampleType == "Pilot", !is.na(TimeSpikedChar)) %>%
  group_by(SurfaceID, EventDate, BatchNumber) %>%
  summarise(EarliestPilotTime_Batch = min(TimeSpikedChar), .groups = "drop")

pilot_times_testorder <- all_dated %>%
  filter(SampleType == "Pilot", !is.na(TimeSpikedChar)) %>%
  group_by(SurfaceID, EventDate, TestOrder) %>%
  summarise(EarliestPilotTime_TO = min(TimeSpikedChar), .groups = "drop")

all_dated <- all_dated %>%
  left_join(pilot_times_batch, by = c("SurfaceID","EventDate","BatchNumber")) %>%
  left_join(pilot_times_testorder, by = c("SurfaceID","EventDate","BatchNumber" = "TestOrder")) %>%
  mutate(
    MatchedTime = coalesce(EarliestPilotTime_Batch, EarliestPilotTime_TO),
    MatchMethod = case_when(
      SampleType != "NC" ~ NA_character_,
      !is.na(EarliestPilotTime_Batch) ~ "BatchNumber match",
      !is.na(EarliestPilotTime_TO) ~ "TestOrder fallback match",
      TRUE ~ "NO MATCH -- orphan (sorts first that day; review manually)"
    ),
    TimeKey = case_when(
      SampleType == "Pilot" & !is.na(TimeSpikedChar) ~ TimeSpikedChar,
      SampleType == "NC" & !is.na(MatchedTime) ~ format(as.POSIXct(MatchedTime, format="%H:%M:%S") - 300, "%H:%M:%S"),
      SampleType == "NC" ~ "00:00:00",
      TRUE ~ "12:00:00"
    )
  )

nc_check <- all_dated[all_dated$SampleType == "NC", c("RunID","SurfaceID","BatchNumber","MatchMethod")]
if (any(nc_check$MatchMethod == "NO MATCH -- orphan (sorts first that day; review manually)")) {
  warning("One or more NCs could not be matched to a batch-mate -- check nc_check above before trusting CumulativeUseNumber.")
}
cat("=== NC match methods (verify no new orphans before trusting usage history) ===\n")
print(nc_check)

usage <- all_dated %>%
  filter(!is.na(SurfaceID)) %>%
  arrange(SurfaceID, EventDate, TimeKey) %>%
  group_by(SurfaceID) %>%
  mutate(CumulativeUseNumber = row_number(), TotalUsesOnThisSurface = n()) %>%
  ungroup()

pilot <- pilot %>%
  left_join(usage %>% filter(SampleType == "Pilot") %>% select(RunID, CumulativeUseNumber, TotalUsesOnThisSurface),
            by = "RunID")

cat("\n=== Total physical uses per surface (pilot + NC) ===\n")
print(usage %>% group_by(SurfaceID) %>%
        summarise(TotalUses = n(), PilotUses = sum(SampleType == "Pilot"), NCUses = sum(SampleType == "NC")))

#-------------------------------------------------------------------------------
# 3. IS THE EFFECT SURFACE-SPECIFIC (e.g. ABS degradation)?
#-------------------------------------------------------------------------------
cat("\n\n========== SECTION 3: Surface-specificity (Surface_type x BatchNumber) ==========\n")
m_interaction <- lmer(RDX_Recovery_pct ~ Surface_type * BatchNumber + Pressure_level + Solvent_level + (1|SurfaceID_nested), data = pilot)
print(anova(m_interaction))
cat("-> If Surface_type:BatchNumber is NOT significant, the batch decline affects both surfaces similarly\n")
cat("   (this was the result as of Aug 2026: p=0.812 -- ruled out as surface-specific).\n")

#-------------------------------------------------------------------------------
# 4. WITHIN-BATCH INJECTION ORDER
#-------------------------------------------------------------------------------
cat("\n\n========== SECTION 4: Within-batch injection order ==========\n")
# IMPORTANT: rank Line only WITHIN the same physical GC-MS sequence
# (Dataset), not just within nominal BatchNumber -- a nominal batch's
# samples are often scattered across multiple different Analysis datasets
# (due to reanalysis), and raw Line numbers are not chronologically
# comparable across different sequences.
pilot_ranked <- pilot %>%
  group_by(Dataset, BatchNumber) %>%
  mutate(WithinBatchRank = rank(Line, ties.method = "first"),
         GroupN = n(),
         WithinBatchRankNorm = (WithinBatchRank - 1) / pmax(GroupN - 1, 1)) %>%
  ungroup()
m_within <- lmer(RDX_Recovery_pct ~ Surface_type * Pressure_level * Solvent_level + BatchNumber + WithinBatchRankNorm + (1|SurfaceID_nested), data = pilot_ranked)
print(anova(m_within)["WithinBatchRankNorm", ])
cat("-> Result as of Aug 2026: p=0.938 -- ruled out.\n")

#-------------------------------------------------------------------------------
# 5. CANDIDATE FACTOR COMPARISON (AIC table vs BatchNumber)
#-------------------------------------------------------------------------------
cat("\n\n========== SECTION 5: Candidate factor AIC comparison ==========\n")
base_f <- "RDX_Recovery_pct ~ Surface_type * Pressure_level * Solvent_level"

m_batch    <- lmer(as.formula(paste(base_f, "+ BatchNumber + (1|SurfaceID_nested)")), data = pilot)
m_platform <- lmer(as.formula(paste(base_f, "+ Platform + (1|SurfaceID_nested)")), data = pilot)
m_swab     <- lmer(as.formula(paste(base_f, "+ SwabBatch + (1|SurfaceID_nested)")), data = pilot)
m_humidity <- lmer(as.formula(paste(base_f, "+ Humidity_pct + (1|SurfaceID_nested)")), data = pilot)
m_extract  <- lmer(as.formula(paste(base_f, "+ ExtractionDelay_days + (1|SurfaceID_nested)")), data = pilot)
m_drying   <- lmer(as.formula(paste(base_f, "+ DryingTime_min + (1|SurfaceID_nested)")), data = pilot)
m_use      <- lmer(as.formula(paste(base_f, "+ CumulativeUseNumber + (1|SurfaceID_nested)")), data = pilot)
m_platbatch<- lmer(as.formula(paste(base_f, "+ Platform + BatchNumber + (1|SurfaceID_nested)")), data = pilot)
m_usebatch <- lmer(as.formula(paste(base_f, "+ CumulativeUseNumber + BatchNumber + (1|SurfaceID_nested)")), data = pilot)

aic_table <- data.frame(
  Model = c("BatchNumber (categorical, baseline)","Platform","SwabBatch","Humidity_pct",
            "ExtractionDelay_days","DryingTime_min","CumulativeUseNumber",
            "Platform + BatchNumber","CumulativeUseNumber + BatchNumber"),
  AIC = c(AIC(m_batch), AIC(m_platform), AIC(m_swab), AIC(m_humidity), AIC(m_extract),
          AIC(m_drying), AIC(m_use), AIC(m_platbatch), AIC(m_usebatch))
)
print(aic_table)
cat("\n-> Lower AIC = better fit. As of Aug 2026, BatchNumber alone (AIC~155.5) beats every\n")
cat("   single candidate factor (AIC~168-177), and none of them reduce BatchNumber's own\n")
cat("   significance when combined with it (see anova() on m_platbatch/m_usebatch for details).\n")

#-------------------------------------------------------------------------------
# 6. SHAPE COMPARISON (linear / quadratic / step / log-scale decay)
#-------------------------------------------------------------------------------
cat("\n\n========== SECTION 6: Shape comparison ==========\n")
pilot$Step_after1 <- factor(pilot$BatchNumeric > 1)
m_linear_days <- lmer(as.formula(paste(base_f, "+ ElapsedDays + (1|SurfaceID_nested)")), data = pilot)
m_quad_days   <- lmer(as.formula(paste(base_f, "+ ElapsedDays + I(ElapsedDays^2) + (1|SurfaceID_nested)")), data = pilot)
m_step1       <- lmer(as.formula(paste(base_f, "+ Step_after1 + (1|SurfaceID_nested)")), data = pilot)

pilot$RDX_log1p <- log1p(pilot$RDX_Recovery_pct)
base_f_log <- "RDX_log1p ~ Surface_type * Pressure_level * Solvent_level"
m_log_days        <- lmer(as.formula(paste(base_f_log, "+ ElapsedDays + (1|SurfaceID_nested)")), data = pilot)
m_log_categorical <- lmer(as.formula(paste(base_f_log, "+ BatchNumber + (1|SurfaceID_nested)")), data = pilot)

shape_table <- data.frame(
  Model = c("Categorical Batch (raw %, most flexible)","Linear in ElapsedDays (raw %)",
            "Quadratic in ElapsedDays (raw %)","Step-change after Batch1 (raw %)",
            "--- log1p scale (fair comparison for decay shape) ---",
            "Log1p ~ linear ElapsedDays","Log1p ~ categorical Batch"),
  AIC = c(AIC(m_batch), AIC(m_linear_days), AIC(m_quad_days), AIC(m_step1),
          NA, AIC(m_log_days), AIC(m_log_categorical))
)
print(shape_table)
cat("\n-> As of Aug 2026: on the raw % scale, NOTHING simple fits well (categorical always wins\n")
cat("   by a wide margin). On the log1p scale, linear decay (~74.6) is much closer to the fully\n")
cat("   flexible fit (~73.4) than on the raw scale -- consistent with an ACCELERATING proportional\n")
cat("   decline (closer to power-law/compounding decay than constant-rate exponential or linear).\n")

cat("\n=== Mean RDX recovery by actual calendar date (re-run to check if the pattern still accelerates) ===\n")
print(pilot %>% group_by(EventDate, ElapsedDays) %>%
        summarise(N = n(), RDX_mean = mean(RDX_Recovery_pct), PETN_mean = mean(PETN_Recovery_pct), .groups = "drop"))

#-------------------------------------------------------------------------------
# 7. IS SELF-CORRECTION CHECK -- is it the analyte or the IS declining?
#-------------------------------------------------------------------------------
cat("\n\n========== SECTION 7: IS self-correction check (analyte vs internal standard) ==========\n")
cat("Internal standard ratio correction should cancel out IS degradation IF the same IS is used\n")
cat("consistently for both calibration standards and real samples each day. Check which part of\n")
cat("the signal chain (rdx_pa = analyte, rdx_is_pa = IS) is actually declining:\n\n")
print(pilot %>% group_by(EventDate, Solvent_level) %>%
        summarise(N = n(), Mean_rdx_pa = mean(rdx_pa, na.rm = TRUE),
                  Mean_rdx_is_pa = mean(rdx_is_pa, na.rm = TRUE), .groups = "drop"))
cat("\n-> As of Aug 2026: rdx_is_pa (IS) stays comparatively stable while rdx_pa (analyte) collapses\n")
cat("   (most clearly within wet/Solvent=present samples, removing the dry-floor-effect confound).\n")
cat("   This points AWAY from 15N-RDX IS stock degradation and TOWARD the RDX spike stock itself,\n")
cat("   or a genuine physical recovery decline, as the more likely explanation.\n")

#-------------------------------------------------------------------------------
# 8. VARIANCE / SIGNIFICANCE CHECK -- is the effect bigger than the noise?
#-------------------------------------------------------------------------------
cat("\n\n========== SECTION 8: Variance check (wet samples only, raw rdx_pa) ==========\n")
wet <- pilot %>% filter(Solvent_level == "present")
wet_stats <- wet %>% group_by(EventDate) %>%
  summarise(N = n(), Mean = mean(rdx_pa, na.rm=TRUE), SD = sd(rdx_pa, na.rm=TRUE),
            SEM = sd(rdx_pa, na.rm=TRUE)/sqrt(n()), CV_pct = 100*sd(rdx_pa,na.rm=TRUE)/mean(rdx_pa,na.rm=TRUE))
print(as.data.frame(wet_stats))
wet$EventDateF <- factor(wet$EventDate)
cat("\nOne-way ANOVA, raw rdx_pa ~ EventDate (wet samples only, unadjusted):\n")
print(summary(aov(rdx_pa ~ EventDateF, data = wet)))
cat("\n-> As of Aug 2026: F(3,12)=4.38, p=0.027 -- significant, but note ~40-45% CV within groups\n")
cat("   and n=1 for one date (no replication) -- treat exact magnitudes with appropriate caution.\n")

#-------------------------------------------------------------------------------
# 9. SUMMARY: what's ruled out, what's not yet tested
#-------------------------------------------------------------------------------
cat("\n\n========== SECTION 9: SUMMARY ==========\n")
cat("
RULED OUT (no meaningful signal, or doesn't explain BatchNumber once combined with it):
  - ABS-specific surface degradation (Section 3)
  - Within-batch injection order / GC-MS drift within a batch (Section 4)
  - ASTRA platform/config change (Section 5)
  - New swab batch / physical swab lot (Section 5)
  - Drying time, spiking-to-swabbing interval (Section 5)
  - Physical surface wear / reuse count, including NC-driven extra uses,
    chronologically corrected (Section 5)

TESTED, SHOW OWN SIGNAL BUT DON'T EXPLAIN THE BATCH EFFECT:
  - Humidity_pct (real negative association, esp. for PETN -- but AIC still far worse than Batch)
  - ExtractionDelay_days (borderline significant but WRONG direction -- longer delay ->
    higher recovery; almost certainly a batch-date confound, not causal)

NOT YET TESTED (candidates for follow-up, see CONTEXT.md session summary for full rationale):
  - Spike stock (PETN+RDX combined solution) age/degradation -- LEADING HYPOTHESIS, given
    Section 7 shows the analyte (not the IS) is what's declining
  - RDX-specific calibration/QC standard stock stability (separate from the spike stock)
  - Ambient lab temperature (not logged, only humidity was)
  - Ethanol (extraction solvent) lot/water content
  - Storage conditions during the extraction delay (fridge vs bench, capped vs open, light exposure)
  - Cotton swab pre-cleaning (acetone soak) duration/thoroughness per batch
")
